main = ".open-next/worker.js"
name = "my-app"
pages_build_output_directory = ".next"
compatibility_date = "2025-01-04"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }
