name: Test Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted, linux]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run a test command
        run: |
          echo "Testing GitHub Actions Runner"
          uname -a
          echo "Success!"
