name: Test Self-Hosted Runner

on:
  push:
    branches:
      - main
  
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for triggering'
        required: false

jobs:
  test:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run a test script
        run: |
          echo "Testing GitHub Actions Runner"
          uname -a
          echo "Success!"
